x-common-php: &common-php
  build:
    context: .
    dockerfile: ./docker/php/Dockerfile
  image: fpm_back
  volumes:
    - ./src/:/var/www/html
  user: www-data
  working_dir: '/var/www/html'
  depends_on:
    service_fpm:
      condition: service_started
  restart: always

services:
  app:
    <<: *common-php
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./src/vendor:/var/www/html/vendor
      - ./src/node_modules:/var/www/html/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - APP_TIMEZONE=Europe/Moscow
    depends_on:
      - db

  service_fpm_scheduler:
    <<: *common-php
    container_name: laravel_scheduler
    environment:
      CONTAINER_ROLE: scheduler
    depends_on:
      - db

  node:
    image: node:22
    container_name: laravel_node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./src/node_modules:/var/www/html/node_modules
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - app

  nginx:
    image: nginx:1.25-alpine
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  redis:
    image: redis:7.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD} --cluster-enabled no
    container_name: laravel_redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

  db:
    image: postgres:15
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: